const string MRK_UID = "{E7A26D55467CEAA3}";
const string MRK_BINOCULAR_RETICLE_UID = "{179C93FC0DB031C9}";

const float MRK_BINOCULAR_TAG_RANGE = 1500.0;
const float MRK_TAG_ACQUISITION_TIME = 1.0;
const int MRK_BINOCULAR_RETICLE_UPDATE_MS = 12;
const int MRK_MARKER_UPDATE_MS = 12;
const int MRK_ALERT_UPDATE_MS = 200;

const float MRK_ICON_HALF_SIZE = 32.0;